import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.gradle.api.tasks.Copy
import org.gradle.internal.os.OperatingSystem
import java.io.File

plugins {
    kotlin("jvm") version "2.1.0"
    kotlin("plugin.serialization") version "2.1.0"
    id("org.jetbrains.kotlin.plugin.compose") version "2.1.0"
    id("org.jetbrains.compose") version "1.7.3"
    // Coverage. There was NO coverage tool at all, so "74 tests" (actually
    // 149) told nobody which of the 5 000 lines of core logic they touched.
    // `gradlew koverHtmlReport` -> build/reports/kover/html/index.html
    id("org.jetbrains.kotlinx.kover") version "0.9.1"
}

/**
 * THE single source of truth for the app version.
 *
 * It used to be hardcoded in five independent places (here twice, Main.kt's
 * sidebar, HomeScreen's footer and SettingsScreen's About card) and they had
 * already drifted — the About card still claimed 3.6.3 while everything else
 * said 3.6.11. The generateBuildInfo task below emits vpn.BuildInfo from this
 * value, and every UI string reads it, so drift is now impossible.
 */
val appVersion = "3.6.17"

group = "com.multivpn"
version = appVersion

kotlin {
    jvmToolchain(17)
}

/** Generates vpn/BuildInfo.kt so the UI can never hardcode a stale version. */
val generatedSrcDir = layout.buildDirectory.dir("generated/buildinfo")

val generateBuildInfo by tasks.registering {
    val outDir = generatedSrcDir
    val v = appVersion
    inputs.property("version", v)
    outputs.dir(outDir)
    doLast {
        val f = outDir.get().file("vpn/BuildInfo.kt").asFile
        f.parentFile.mkdirs()
        f.writeText(
            """
            package vpn

            /** GENERATED by the Gradle `generateBuildInfo` task - do not edit. */
            object BuildInfo {
                const val VERSION: String = "$v"
                const val ARCH: String = "x86_64"
                /** "v3.6.12 · x86_64" */
                val LABEL: String get() = "v${'$'}VERSION · ${'$'}ARCH"
            }

            """.trimIndent(),
        )
    }
}

sourceSets.main { kotlin.srcDir(generateBuildInfo) }

tasks.test {
    useJUnitPlatform()
    // TEST ISOLATION (critical): pin Storage's data directory to a scratch
    // dir. Storage honours -Dmultivpn.dataDir; without this the whole test
    // suite read/wrote the developer's REAL %APPDATA%\MultiVPN — a full
    // `gradlew test` silently overwrote the live servers.json / configs.json /
    // settings.json with fixture data (real data loss reported 2 Sep 2026).
    jvmArgs("-Dmultivpn.dataDir=${layout.buildDirectory.dir("test-data").get().asFile.absolutePath}")
}

/**
 * Coverage scope: the `vpn.core` logic is what tests can actually reach.
 * Compose UI, the generated BuildInfo and the app entry point are excluded so
 * the number means something instead of being diluted to noise by 5 000 lines
 * of @Composable that no unit test can execute.
 */
kover {
    reports {
        filters {
            excludes {
                packages("vpn.ui", "vpn.theme")
                classes("vpn.MainKt", "vpn.BuildInfo", "vpn.NavItem", "vpn.ComposableSingletons*")
            }
        }
    }
}

dependencies {
    implementation(compose.desktop.currentOs)
    implementation(compose.material3)
    implementation(compose.materialIconsExtended)
    // Coroutines 1.10.2 is the last line that pairs with Kotlin 2.1 without
    // pulling the 2.2-era stdlib expectations of 1.11.x.
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-swing:1.10.2")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")
    // sshj 0.40.0: 0.38.0 was the first release WITH the Terrapin
    // (CVE-2023-48795) fix, but it also carries older BouncyCastle
    // (1.75) with known transitive advisories. 0.40.0 ships bcprov 1.78.x.
    implementation("com.hierynomus:sshj:0.40.0")
    implementation("org.slf4j:slf4j-simple:2.0.18")
    implementation("net.java.dev.jna:jna:5.19.1")
    implementation("net.java.dev.jna:jna-platform:5.19.1")

    testImplementation(kotlin("test"))
    testImplementation("org.junit.jupiter:junit-jupiter:5.14.4")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

compose.desktop {
    application {
        mainClass = "vpn.MainKt"
        nativeDistributions {
            // AppImage = the portable app folder (plain jpackage, no WiX):
            //   gradlew createDistributable
            //   -> build/compose/binaries/main/app/MultiVPN/MultiVPN.exe
            // Msi/Exe are the installers; they REQUIRE WiX 3.x on the build
            // machine (GitHub's windows-latest image ships it):
            //   gradlew packageMsi packageExe
            //   -> build/compose/binaries/main/{msi,exe}/MultiVPN-<ver>.{msi,exe}
            //
            // All three MUST be declared here. Declaring only AppImage meant
            // the packageMsi/packageExe tasks did not exist at all, so the CI
            // workflow and the README both referenced tasks Gradle rejected
            // with "Task 'packageMsi' not found" — no CI run could ever pass.
            //
            // WARNING: Gradle's plain `build` lifecycle never runs any
            // packaging task - call them explicitly (desktop\build.bat does).
            targetFormats(TargetFormat.AppImage, TargetFormat.Msi, TargetFormat.Exe)
            packageName = "MultiVPN"
            packageVersion = appVersion
            description = "MultiVPN - multi-protocol VPN client"
            vendor = "MultiVPN"
            windows {
                iconFile = project.file("icon\\multivpn-shield-m.ico")
                upgradeUuid = "8e2f7a41-6c3b-4d9e-9f5a-2b7c8d1e4a6f"
                console = false
                menu = true
                shortcut = true
            }
            // Modules the bundled jlink runtime must contain. This list is NOT
            // cosmetic: jpackage builds a minimal runtime from exactly these,
            // and anything missing fails only in the PACKAGED app (never in
            // `gradle run`, which uses the full JDK) — the worst class of bug.
            //
            // Verified with:
            //   jdeps --multi-release 17 --print-module-deps --ignore-missing-deps \
            //     -cp "<all app jars>" multivpn-<ver>.jar
            // which reports: java.base java.desktop java.instrument java.naming
            //                java.net.http java.security.jgss java.sql jdk.unsupported
            //
            //  java.net.http        MSI/subscription/core downloads
            //  jdk.crypto.ec        SSH host keys (sshj), EC TLS
            //  java.security.jgss   sshj's AuthGssApiWithMic — reflection over
            //                       SSHClient's methods threw
            //                       NoClassDefFoundError: org/ietf/jgss/Oid
            //                       without it (reproduced with --limit-modules)
            //  java.naming          BouncyCastle CRL/LDAP cert-store paths
            //  java.sql             BouncyCastle LDAPStoreHelper
            //  java.instrument      kotlinx-coroutines debug AgentPremain
            //  jdk.unsupported      sun.misc.Unsafe (Kotlin/Compose internals)
            modules(
                "java.net.http", "jdk.crypto.ec", "java.security.jgss",
                "java.naming", "java.sql", "java.instrument", "jdk.unsupported",
            )
        }
    }
}

// Compose's jpackage backend occasionally ignores iconFile when the source
// is a PNG-wrapped ICO. A post-packaging copy keeps the resource bundled for
// the runtime while the jpackage Windows block uses the valid ICO for exe.

